//! Serves Telegram Desktop's update protocol for Tlgrm.
//!
//! Telegram Desktop's HTTP updater asks a single question — "is there a
//! version newer than mine, and where is it?" — and answers it from one JSON
//! document at `{prefix}/current<N>`, where N is the updater generation
//! (`Platform::AutoUpdateVersion()`, 4 on current macOS). It then downloads
//! the package named in that document's `link`, relative to the same prefix.
//!
//! So this serves exactly two things:
//!
//!   GET /current           the manifest, derived from what is on disk
//!   GET /tarmacupd7000007  the package itself
//!
//! The manifest is generated by looking at the package directory rather than
//! being written by hand, because a manifest that disagrees with the packages
//! present is the failure this whole subsystem exists to avoid: the client
//! downloads, verifies, and silently does nothing. Files on disk are the one
//! source of truth, and they cannot drift from themselves.
//!
//! Nothing here talks to GitHub or Telegram. It answers from local files, so
//! it keeps working on the LAN when nothing else does — which is the point of
//! hosting it rather than depending on someone else's CDN.

use std::{
    collections::BTreeMap,
    net::SocketAddr,
    path::{Path, PathBuf},
};

use axum::{
    body::Body,
    extract::State,
    http::{header, StatusCode},
    response::{IntoResponse, Response},
    routing::get,
    Router,
};
use tokio::net::TcpListener;

/// A package found on disk.
///
/// The filename carries everything needed: `tarmacupd7000007` is the Apple
/// Silicon build of version 7000007. Telegram's own packer produces these
/// names, so parsing them is reading its output rather than inventing a
/// convention.
#[derive(Debug, Clone)]
struct Package {
    /// `armac` or `mac` — the key `Platform::AutoUpdateKey()` looks up.
    platform: &'static str,
    /// `AppVersion` as an integer, e.g. 7000007 for 7.0.7.
    version: u64,
    file_name: String,
}

/// Package name prefixes, mapped to the platform key the client asks for.
///
/// `armac` is Apple Silicon (and Intel binaries running under Rosetta);
/// `mac` is native Intel. A universal build is published under both names so
/// either client finds it, which is why the same bytes can appear twice.
const PREFIXES: &[(&str, &str)] = &[("tarmacupd", "armac"), ("tmacupd", "mac")];

#[derive(Clone)]
struct AppState {
    packages_dir: PathBuf,
}

impl Package {
    /// Parses `tarmacupd7000007`, or `None` if the name is anything else.
    ///
    /// Deliberately strict: a partially-uploaded file named `tarmacupd7000007.tmp`
    /// must not be advertised, or clients download a truncated package and the
    /// signature check fails for a reason no one can see from here.
    fn parse(file_name: &str) -> Option<Self> {
        for (prefix, platform) in PREFIXES {
            if let Some(rest) = file_name.strip_prefix(prefix) {
                if rest.is_empty() || !rest.bytes().all(|b| b.is_ascii_digit()) {
                    continue;
                }
                return Some(Package {
                    platform,
                    version: rest.parse().ok()?,
                    file_name: file_name.to_string(),
                });
            }
        }
        None
    }
}

/// The newest package per platform, read fresh from disk.
///
/// Read per request rather than cached: publishing is dropping a file in a
/// directory, and a cache would mean a published update stays invisible until
/// someone restarts the service. The directory holds a handful of entries, so
/// the read costs nothing worth optimising.
fn newest_per_platform(dir: &Path) -> BTreeMap<&'static str, Package> {
    let mut best: BTreeMap<&'static str, Package> = BTreeMap::new();
    let entries = match std::fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(error) => {
            tracing::warn!(?dir, %error, "cannot read package directory");
            return best;
        }
    };
    for entry in entries.flatten() {
        if !entry.file_type().map(|t| t.is_file()).unwrap_or(false) {
            continue;
        }
        let name = entry.file_name();
        let Some(name) = name.to_str() else { continue };
        let Some(package) = Package::parse(name) else { continue };
        best.entry(package.platform)
            .and_modify(|current| {
                if package.version > current.version {
                    *current = package.clone();
                }
            })
            .or_insert(package);
    }
    best
}

/// Builds the manifest the client parses in `ParseCommonMap`.
///
/// Shape is dictated by the client, not chosen here:
///
/// ```json
/// {"armac": {"stable": {"released": "7000007", "link": "/tarmacupd7000007"}}}
/// ```
///
/// `released` is a string because the client reads it through a path that
/// accepts either form, and a 64-bit version as a JSON number would round
/// through a double. `link` is relative — the client concatenates it onto the
/// same prefix it fetched the manifest from.
fn manifest(packages: &BTreeMap<&'static str, Package>) -> serde_json::Value {
    let mut root = serde_json::Map::new();
    for (platform, package) in packages {
        root.insert(
            (*platform).to_string(),
            serde_json::json!({
                "stable": {
                    "released": package.version.to_string(),
                    "link": format!("/{}", package.file_name),
                }
            }),
        );
    }
    serde_json::Value::Object(root)
}

async fn current(State(state): State<AppState>) -> Response {
    let packages = newest_per_platform(&state.packages_dir);
    if packages.is_empty() {
        // 503, not an empty manifest. An empty object parses fine and reads as
        // "you are up to date", which would hide a publishing mistake for as
        // long as nobody looked. This says the server has nothing to offer.
        return (
            StatusCode::SERVICE_UNAVAILABLE,
            [(header::CONTENT_TYPE, "application/json")],
            r#"{"error":"no update packages present"}"#,
        )
            .into_response();
    }
    (
        StatusCode::OK,
        [
            (header::CONTENT_TYPE, "application/json"),
            // The manifest is the thing that must never be stale: a cached copy
            // outlives the release it describes and clients keep being offered
            // a version that is no longer newest.
            (header::CACHE_CONTROL, "no-cache"),
        ],
        manifest(&packages).to_string(),
    )
        .into_response()
}

/// Serves a package by name.
///
/// Only names that parse as packages are served. This is not a file server
/// with a filter bolted on — nothing else in the directory is reachable, so a
/// stray `.env` or a key placed there by accident cannot be fetched, and no
/// path traversal is possible because the name never becomes a path component
/// until it has been validated as `<prefix><digits>`.
async fn package(
    State(state): State<AppState>,
    axum::extract::Path(name): axum::extract::Path<String>,
) -> Response {
    let Some(package) = Package::parse(&name) else {
        return (StatusCode::NOT_FOUND, "not an update package").into_response();
    };
    let path = state.packages_dir.join(&package.file_name);
    let file = match tokio::fs::File::open(&path).await {
        Ok(file) => file,
        Err(error) => {
            tracing::warn!(%name, %error, "package listed but not readable");
            return (StatusCode::NOT_FOUND, "no such package").into_response();
        }
    };
    let len = file.metadata().await.map(|m| m.len()).unwrap_or(0);
    let stream = stream_file(file);
    (
        StatusCode::OK,
        [
            (header::CONTENT_TYPE, "application/octet-stream".to_string()),
            (header::CONTENT_LENGTH, len.to_string()),
            // Packages are immutable: the version is in the name, so a given
            // name always denotes the same bytes and can be cached hard.
            (
                header::CACHE_CONTROL,
                "public, max-age=31536000, immutable".to_string(),
            ),
        ],
        stream,
    )
        .into_response()
}

/// Streams a file as a body rather than buffering it.
///
/// Packages are ~75 MB; reading one into memory per request would cost more
/// RSS than the rest of the service uses, on a box with 1.7 GB total.
fn stream_file(file: tokio::fs::File) -> Body {
    Body::from_stream(tokio_util::io::ReaderStream::with_capacity(file, 64 * 1024))
}

/// Liveness plus what the server can currently see.
///
/// Reports the packages it would advertise, so "is it up" and "does it have
/// anything to serve" are answerable in one request — the second question is
/// the one that actually goes wrong.
async fn health(State(state): State<AppState>) -> Response {
    let packages = newest_per_platform(&state.packages_dir);
    let body = serde_json::json!({
        "ok": true,
        "packages_dir": state.packages_dir.to_string_lossy(),
        "packages": packages
            .values()
            .map(|p| serde_json::json!({
                "platform": p.platform,
                "version": p.version,
                "file": p.file_name,
            }))
            .collect::<Vec<_>>(),
    });
    (
        StatusCode::OK,
        [(header::CONTENT_TYPE, "application/json")],
        body.to_string(),
    )
        .into_response()
}

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "info".into()),
        )
        .init();

    let packages_dir = PathBuf::from(
        std::env::var("TLGRM_PACKAGES_DIR").unwrap_or_else(|_| "/srv/tlgrm-updates".into()),
    );
    let addr: SocketAddr = std::env::var("TLGRM_LISTEN")
        .unwrap_or_else(|_| "127.0.0.1:8083".into())
        .parse()
        .expect("TLGRM_LISTEN must be host:port");

    // "/current" is what our client asks for: it appends no generation
    // suffix, because we ship one build for one OS generation. The suffixed
    // paths are kept so an install from before that change, or a stock
    // Telegram Desktop pointed here, still gets an answer rather than a 404.
    let app = Router::new()
        .route("/current", get(current))
        .route("/current4", get(current))
        .route("/current2", get(current))
        .route("/health", get(health))
        .route("/:name", get(package))
        .with_state(AppState {
            packages_dir: packages_dir.clone(),
        });

    tracing::info!(?packages_dir, %addr, "tlgrm-updates starting");
    let listener = TcpListener::bind(addr).await.expect("cannot bind");
    axum::serve(listener, app)
        .with_graceful_shutdown(shutdown())
        .await
        .expect("server failed");
}

/// Finishes in-flight downloads before exiting.
///
/// A package transfer takes tens of seconds; dropping them on SIGTERM would
/// leave clients with truncated files that fail signature verification, which
/// looks like a corrupt release rather than a restart.
async fn shutdown() {
    let _ = tokio::signal::ctrl_c().await;
    tracing::info!("shutting down");
}
