// This file is part of Telegram Desktop MCP integration.
//
// For license and copyright information please follow this link:
// https://github.com/telegramdesktop/tdesktop/blob/master/LEGAL
#pragma once

#include <QtCore/QStringList>

#include <array>
#include <string_view>

namespace MCP {

// What actually answers a tool call.
//
// A tool used to be declared in three hand-synced places -- a header
// signature, a schema entry in registerTools(), and a lambda in the
// _toolHandlers map -- with nothing linking them. That let one tool get
// advertised twice, five get their handler assigned twice, and eight become
// callable while never being advertised at all. Worse, nothing recorded
// whether a tool had any data source, so tools that invented their answer
// reported success indistinguishably from tools that queried Telegram.
//
// This table is the single place that records what backs each tool. The
// server consults it on every call, so a tool nothing backs cannot report
// success no matter what its implementation does.
enum class Backing {
	// Issues Telegram API requests. The answer comes from Telegram.
	Mtproto,

	// Reads live session state already synced from Telegram.
	LiveSession,

	// Derives its answer from its arguments alone -- no I/O, no state.
	// Honest and deterministic; simply not a Telegram query.
	PureCompute,

	// Reads or writes only this client's local database. Nothing syncs that
	// database from Telegram, so results describe local state and must not
	// be read as Telegram's view of the world.
	LocalOnly,

	// Nothing backs this tool. It must never report success: returning
	// success here is what made 20 tools indistinguishable from working
	// ones. Callers get an explicit error instead.
	Unimplemented,
};

struct ToolBackingEntry {
	std::string_view name;
	Backing backing;
};

// Sorted by name; ToolBackingFor() relies on that for a binary search and
// a debug assert verifies it at startup.
inline constexpr std::array kToolBackings = std::to_array<ToolBackingEntry>({
	{"add_chat_to_community",         Backing::Mtproto },
	{"add_message_tag",               Backing::LocalOnly },
	{"add_reaction",                  Backing::LiveSession },
	{"add_to_collection",             Backing::Mtproto },
	{"approve_miniapp_spend",         Backing::LocalOnly },
	{"archive_chat",                  Backing::LocalOnly },
	{"archive_deleted_accounts",      Backing::LiveSession },
	{"auto_translate_chat",           Backing::LocalOnly },
	{"backtest_strategy",             Backing::LocalOnly },
	{"batch_delete",                  Backing::LiveSession },
	{"batch_forward",                 Backing::Mtproto },
	{"batch_pin",                     Backing::Mtproto },
	{"batch_reaction",                Backing::LiveSession },
	{"batch_send",                    Backing::Mtproto },
	{"block_user",                    Backing::Mtproto },
	{"browse_gift_marketplace",       Backing::Mtproto },
	{"buy_gift",                      Backing::Unimplemented },
	{"cancel_deleted_archive",        Backing::LocalOnly },
	{"cancel_gradual_export",         Backing::LocalOnly },
	{"cancel_listing",                Backing::Mtproto },
	{"cancel_scheduled",              Backing::LocalOnly },
	{"cancel_subscription",           Backing::Mtproto },
	{"categorize_transaction",        Backing::LocalOnly },
	{"check_business_status",         Backing::LocalOnly },
	{"check_channel_username",        Backing::Mtproto },
	{"claim_achievement_reward",      Backing::LocalOnly },
	{"classify_intent",               Backing::PureCompute },
	{"clear_finished_downloads",      Backing::LiveSession },
	{"clone_voice",                   Backing::LocalOnly },
	{"configure_ad_filter",           Backing::LocalOnly },
	{"configure_ai_chatbot",          Backing::LocalOnly },
	{"configure_away_message",        Backing::LocalOnly },
	{"configure_bot",                 Backing::LocalOnly },
	{"configure_chatbot",             Backing::LocalOnly },
	{"configure_ephemeral_capture",   Backing::LocalOnly },
	{"configure_greeting",            Backing::LocalOnly },
	{"configure_paid_messages",       Backing::LocalOnly },
	{"configure_video_avatar",        Backing::LocalOnly },
	{"configure_voice_persona",       Backing::LocalOnly },
	{"configure_wallet_alerts",       Backing::LocalOnly },
	{"convert_stars",                 Backing::LiveSession },
	{"craft_star_gift",               Backing::Mtproto },
	{"create_auction_alert",          Backing::LocalOnly },
	{"create_auto_reply_rule",        Backing::LocalOnly },
	{"create_channel",                Backing::Mtproto },
	{"create_chat_rule",              Backing::LocalOnly },
	{"create_community",              Backing::Mtproto },
	{"create_crypto_payment",         Backing::LocalOnly },
	{"create_exclusive_content",      Backing::LocalOnly },
	{"create_folder",                 Backing::Mtproto },
	{"create_gift_collection",        Backing::Mtproto },
	{"create_giveaway",               Backing::Mtproto },
	{"create_paid_post",              Backing::LocalOnly },
	{"create_price_alert",            Backing::LocalOnly },
	{"create_quick_reply",            Backing::LocalOnly },
	{"create_task",                   Backing::LiveSession },
	{"create_task_from_message",      Backing::LiveSession },
	{"delete_auto_reply_rule",        Backing::LocalOnly },
	{"delete_channel",                Backing::Mtproto },
	{"delete_chat_rule",              Backing::LocalOnly },
	{"delete_downloaded_files",       Backing::LiveSession },
	{"delete_folder",                 Backing::LiveSession },
	{"delete_gift_collection",        Backing::Mtproto },
	{"delete_message",                Backing::LiveSession },
	{"delete_quick_reply",            Backing::LocalOnly },
	{"delete_tag",                    Backing::LocalOnly },
	{"delist_gift",                   Backing::Mtproto },
	{"detect_topics",                 Backing::LocalOnly },
	{"disable_away",                  Backing::LocalOnly },
	{"disable_greeting",              Backing::LocalOnly },
	{"edit_message",                  Backing::LiveSession },
	{"edit_quick_reply",              Backing::LocalOnly },
	{"execute_chat_rules",            Backing::LocalOnly },
	{"export_analytics",              Backing::LocalOnly },
	{"export_chat",                   Backing::LiveSession },
	{"export_portfolio_report",       Backing::LocalOnly },
	{"export_topic",                  Backing::Mtproto },
	{"export_transactions",           Backing::LocalOnly },
	{"extract_entities",              Backing::PureCompute },
	{"forward_message",               Backing::Mtproto },
	{"generate_financial_report",     Backing::LocalOnly },
	{"generate_video_circle",         Backing::LocalOnly },
	{"generate_voice_message",        Backing::LocalOnly },
	{"get_achievement_progress",      Backing::LocalOnly },
	{"get_achievement_suggestions",   Backing::LocalOnly },
	{"get_active_sessions",           Backing::Mtproto },
	{"get_ad_filter_stats",           Backing::LocalOnly },
	{"get_all_channels_earnings",     Backing::LocalOnly },
	{"get_archive_stats",             Backing::LocalOnly },
	{"get_auction_alerts",            Backing::LocalOnly },
	{"get_auction_details",           Backing::Mtproto },
	{"get_auction_history",           Backing::Mtproto },
	{"get_auction_status",            Backing::Mtproto },
	{"get_audit_log",                 Backing::LocalOnly },
	{"get_auto_download_settings",    Backing::LiveSession },
	{"get_auto_reply_stats",          Backing::LocalOnly },
	{"get_away_config",               Backing::LocalOnly },
	{"get_away_message",              Backing::LocalOnly },
	{"get_away_stats",                Backing::LocalOnly },
	{"get_balance_history",           Backing::LocalOnly },
	{"get_blocked_users",             Backing::Mtproto },
	{"get_bot_info",                  Backing::LocalOnly },
	{"get_bot_stats",                 Backing::LocalOnly },
	{"get_bot_suggestions",           Backing::LocalOnly },
	{"get_budget_status",             Backing::LocalOnly },
	{"get_business_hours",            Backing::LocalOnly },
	{"get_business_location",         Backing::LocalOnly },
	{"get_cache_stats",               Backing::LocalOnly },
	{"get_channel_earnings",          Backing::LocalOnly },
	{"get_chat_activity",             Backing::LocalOnly },
	{"get_chat_info",                 Backing::LiveSession },
	{"get_chat_rules",                Backing::LocalOnly },
	{"get_chatbot_analytics",         Backing::LocalOnly },
	{"get_chatbot_config",            Backing::LocalOnly },
	{"get_chatbot_stats",             Backing::LocalOnly },
	{"get_collectibles_portfolio",    Backing::LocalOnly },
	{"get_collection_completion",     Backing::Mtproto },
	{"get_collection_details",        Backing::Mtproto },
	{"get_community",                 Backing::LiveSession },
	{"get_craft_options",             Backing::Mtproto },
	{"get_creator_dashboard",         Backing::LocalOnly },
	{"get_deleted_archive_status",    Backing::LocalOnly },
	{"get_earnings",                  Backing::Mtproto },
	{"get_earnings_chart",            Backing::LocalOnly },
	{"get_ephemeral_messages",        Backing::LocalOnly },
	{"get_ephemeral_stats",           Backing::LocalOnly },
	{"get_export_status",             Backing::LocalOnly },
	{"get_filtered_ads",              Backing::LocalOnly },
	{"get_fragment_listings",         Backing::Mtproto },
	{"get_gift_analytics",            Backing::LocalOnly },
	{"get_gift_details",              Backing::Mtproto },
	{"get_gift_history",              Backing::LocalOnly },
	{"get_gift_investment_advice",    Backing::LocalOnly },
	{"get_gift_price_history",        Backing::LocalOnly },
	{"get_gift_suggestions",          Backing::Mtproto },
	{"get_gift_transfer_history",     Backing::LocalOnly },
	{"get_giveaway_options",          Backing::Mtproto },
	{"get_giveaway_stats",            Backing::LocalOnly },
	{"get_gradual_export_config",     Backing::LocalOnly },
	{"get_gradual_export_queue",      Backing::LocalOnly },
	{"get_gradual_export_status",     Backing::LocalOnly },
	{"get_greeting_config",           Backing::LocalOnly },
	{"get_greeting_message",          Backing::LocalOnly },
	{"get_greeting_stats",            Backing::LocalOnly },
	{"get_income_analytics",          Backing::LocalOnly },
	{"get_leaderboard",               Backing::LocalOnly },
	{"get_market_trends",             Backing::LocalOnly },
	{"get_message_stats",             Backing::LocalOnly },
	{"get_message_tags",              Backing::LocalOnly },
	{"get_miniapp_history",           Backing::LocalOnly },
	{"get_miniapp_spending",          Backing::LocalOnly },
	{"get_monetization_analytics",    Backing::Mtproto },
	{"get_next_available_slot",       Backing::LocalOnly },
	{"get_paid_content_earnings",     Backing::LocalOnly },
	{"get_paid_content_stats",        Backing::LocalOnly },
	{"get_paid_media_stats",          Backing::LocalOnly },
	{"get_paid_messages_stats",       Backing::LocalOnly },
	{"get_portfolio",                 Backing::LocalOnly },
	{"get_portfolio_history",         Backing::LocalOnly },
	{"get_portfolio_performance",     Backing::LocalOnly },
	{"get_portfolio_value",           Backing::LocalOnly },
	{"get_price_predictions",         Backing::LocalOnly },
	{"get_privacy_settings",          Backing::Mtproto },
	{"get_profile_gifts",             Backing::LocalOnly },
	{"get_profile_settings",          Backing::LiveSession },
	{"get_rating_history",            Backing::LocalOnly },
	{"get_reaction_analytics",        Backing::LocalOnly },
	{"get_reaction_stats",            Backing::LocalOnly },
	{"get_security_settings",         Backing::Mtproto },
	{"get_server_info",               Backing::LocalOnly },
	{"get_spending_analytics",        Backing::LocalOnly },
	{"get_star_gift_details",         Backing::LocalOnly },
	{"get_star_rating",               Backing::LocalOnly },
	{"get_star_rating_details",       Backing::LocalOnly },
	{"get_star_reactions",            Backing::LocalOnly },
	{"get_star_reactions_received",   Backing::LocalOnly },
	{"get_star_reactions_sent",       Backing::LocalOnly },
	{"get_stars_history",             Backing::Mtproto },
	{"get_stars_leaderboard",         Backing::LocalOnly },
	{"get_stars_rate",                Backing::LiveSession },
	{"get_subscriber_analytics",      Backing::LocalOnly },
	{"get_subscription_alerts",       Backing::LocalOnly },
	{"get_subscription_stats",        Backing::LocalOnly },
	{"get_tag_suggestions",           Backing::LocalOnly },
	{"get_tagged_messages",           Backing::LocalOnly },
	{"get_tax_summary",               Backing::LocalOnly },
	{"get_time_series",               Backing::LocalOnly },
	{"get_top_reacted",               Backing::LocalOnly },
	{"get_top_supporters",            Backing::LocalOnly },
	{"get_top_users",                 Backing::LocalOnly },
	{"get_top_words",                 Backing::LocalOnly },
	{"get_topup_options",             Backing::Mtproto },
	{"get_transaction_details",       Backing::LocalOnly },
	{"get_transactions",              Backing::LocalOnly },
	{"get_transcription",             Backing::LocalOnly },
	{"get_transcription_status",      Backing::LocalOnly },
	{"get_translation_history",       Backing::LocalOnly },
	{"get_translation_languages",     Backing::PureCompute },
	{"get_trends",                    Backing::LocalOnly },
	{"get_unique_gift_analytics",     Backing::LocalOnly },
	{"get_unlocked_content",          Backing::LocalOnly },
	{"get_upgrade_options",           Backing::Mtproto },
	{"get_user_activity",             Backing::LocalOnly },
	{"get_user_info",                 Backing::LiveSession },
	{"get_voice_transcription",       Backing::LocalOnly },
	{"get_wallet_balance",            Backing::Mtproto },
	{"get_withdrawal_status",         Backing::LocalOnly },
	{"health_check",                  Backing::LocalOnly },
	{"index_messages",                Backing::LiveSession },
	{"is_open_now",                   Backing::LocalOnly },
	{"list_achievements",             Backing::PureCompute },
	{"list_active_auctions",          Backing::Mtproto },
	{"list_archived_chats",           Backing::LocalOnly },
	{"list_auctions",                 Backing::Mtproto },
	{"list_auto_reply_rules",         Backing::LocalOnly },
	{"list_available_gifts",          Backing::Mtproto },
	{"list_avatar_presets",           Backing::LocalOnly },
	{"list_bots",                     Backing::LocalOnly },
	{"list_chat_rules",               Backing::LocalOnly },
	{"list_chats",                    Backing::LiveSession },
	{"list_communities",              Backing::Mtproto },
	{"list_community_join_requests",  Backing::Mtproto },
	{"list_deleted_accounts",         Backing::LiveSession },
	{"list_deleted_channels",         Backing::LiveSession },
	{"list_downloads",                Backing::LiveSession },
	{"list_folders",                  Backing::LiveSession },
	{"list_gift_collections",         Backing::Mtproto },
	{"list_gift_for_sale",            Backing::Mtproto },
	{"list_gifts",                    Backing::Mtproto },
	{"list_giveaways",                Backing::LocalOnly },
	{"list_marketplace",              Backing::Mtproto },
	{"list_miniapp_permissions",      Backing::LocalOnly },
	{"list_purchased_content",        Backing::LocalOnly },
	{"list_quick_replies",            Backing::LocalOnly },
	{"list_rich_messages",            Backing::LiveSession },
	{"list_scheduled",                Backing::LocalOnly },
	{"list_star_gifts",               Backing::Mtproto },
	{"list_subscriptions",            Backing::Mtproto },
	{"list_tags",                     Backing::LocalOnly },
	{"list_tasks",                    Backing::LocalOnly },
	{"list_topics",                   Backing::LiveSession },
	{"list_voice_personas",           Backing::LocalOnly },
	{"list_voice_presets",            Backing::LocalOnly },
	{"pause_chatbot",                 Backing::LocalOnly },
	{"pause_deleted_archive",         Backing::LocalOnly },
	{"pause_gradual_export",          Backing::LocalOnly },
	{"pin_message",                   Backing::Mtproto },
	{"place_auction_bid",             Backing::Unimplemented },
	{"place_bid",                     Backing::Unimplemented },
	{"purge_archive",                 Backing::LocalOnly },
	{"queue_gradual_export",          Backing::LiveSession },
	{"read_messages",                 Backing::LiveSession },
	{"refund_content",                Backing::LocalOnly },
	{"remove_chat_from_community",    Backing::Mtproto },
	{"remove_from_collection",        Backing::Mtproto },
	{"remove_message_tag",            Backing::LocalOnly },
	{"rename_chat",                   Backing::Mtproto },
	{"reorder_folders",               Backing::LiveSession },
	{"reorder_profile_gifts",         Backing::Mtproto },
	{"request_message_summary",       Backing::Mtproto },
	{"request_stars",                 Backing::LiveSession },
	{"resume_chatbot",                Backing::LocalOnly },
	{"resume_deleted_archive",        Backing::LocalOnly },
	{"resume_gradual_export",         Backing::LocalOnly },
	{"review_community_join_request", Backing::Mtproto },
	{"revoke_miniapp_permission",     Backing::LocalOnly },
	{"save_rich_message_html",        Backing::LiveSession },
	{"schedule_message",              Backing::LocalOnly },
	{"search_archive",                Backing::LocalOnly },
	{"search_by_tag",                 Backing::LocalOnly },
	{"search_messages",               Backing::LiveSession },
	{"search_transactions",           Backing::LocalOnly },
	{"semantic_index_messages",       Backing::LiveSession },
	{"semantic_search",               Backing::LocalOnly },
	{"send_bot_command",              Backing::LocalOnly },
	{"send_document",                 Backing::Mtproto },
	{"send_gift",                     Backing::Mtproto },
	{"send_message",                  Backing::Mtproto },
	{"send_quick_reply",              Backing::Mtproto },
	{"send_star_gift",                Backing::Mtproto },
	{"send_star_reaction",            Backing::LocalOnly },
	{"send_stars",                    Backing::Unimplemented },
	{"send_subscriber_message",       Backing::Mtproto },
	{"send_video_reply",              Backing::Mtproto },
	{"send_voice_reply",              Backing::Mtproto },
	{"set_auto_download_settings",    Backing::LiveSession },
	{"set_away_message",              Backing::LocalOnly },
	{"set_away_now",                  Backing::LocalOnly },
	{"set_budget_alert",              Backing::LocalOnly },
	{"set_business_hours",            Backing::LocalOnly },
	{"set_business_location",         Backing::LocalOnly },
	{"set_channel_username",          Backing::Mtproto },
	{"set_chat_rules",                Backing::LocalOnly },
	{"set_chatbot_prompt",            Backing::LocalOnly },
	{"set_community_collapsed",       Backing::LiveSession },
	{"set_content_price",             Backing::LocalOnly },
	{"set_gradual_export_config",     Backing::LiveSession },
	{"set_greeting_message",          Backing::LocalOnly },
	{"set_miniapp_budget",            Backing::LocalOnly },
	{"set_monetization_rules",        Backing::LocalOnly },
	{"set_price_alert",               Backing::LocalOnly },
	{"set_reaction_price",            Backing::Mtproto },
	{"set_spending_budget",           Backing::LocalOnly },
	{"set_subscriber_tiers",          Backing::LocalOnly },
	{"set_wallet_budget",             Backing::LocalOnly },
	{"share_achievement",             Backing::Mtproto },
	{"simulate_rating_change",        Backing::LocalOnly },
	{"start_bot",                     Backing::LocalOnly },
	{"start_gradual_export",          Backing::LiveSession },
	{"stop_bot",                      Backing::LocalOnly },
	{"subscribe_to_channel",          Backing::LocalOnly },
	{"tag_message",                   Backing::LocalOnly },
	{"terminate_session",             Backing::Mtproto },
	{"test_auto_reply_rule",          Backing::LocalOnly },
	{"test_away",                     Backing::Mtproto },
	{"test_chat_rules",               Backing::LocalOnly },
	{"test_chatbot",                  Backing::LocalOnly },
	{"test_greeting",                 Backing::Mtproto },
	{"text_to_speech",                Backing::LocalOnly },
	{"text_to_video",                 Backing::LocalOnly },
	{"toggle_gift_notifications",     Backing::Mtproto },
	{"train_chatbot",                 Backing::LocalOnly },
	{"transcribe_voice",              Backing::LocalOnly },
	{"transcribe_voice_message",      Backing::LiveSession },
	{"transfer_gift",                 Backing::Mtproto },
	{"transfer_group_ownership",      Backing::Mtproto },
	{"translate_message",             Backing::LiveSession },
	{"translate_messages",            Backing::LiveSession },
	{"unblock_user",                  Backing::Mtproto },
	{"unlock_content",                Backing::LocalOnly },
	{"unpin_message",                 Backing::Mtproto },
	{"unsubscribe_from_channel",      Backing::Mtproto },
	{"update_about_privacy",          Backing::Mtproto },
	{"update_auto_delete_period",     Backing::Mtproto },
	{"update_auto_reply_rule",        Backing::LocalOnly },
	{"update_birthday_privacy",       Backing::Mtproto },
	{"update_folder",                 Backing::Mtproto },
	{"update_forwards_privacy",       Backing::Mtproto },
	{"update_gift_display",           Backing::Mtproto },
	{"update_last_seen_privacy",      Backing::Mtproto },
	{"update_listing",                Backing::Mtproto },
	{"update_phone_number_privacy",   Backing::Mtproto },
	{"update_profile_bio",            Backing::Mtproto },
	{"update_profile_name",           Backing::Mtproto },
	{"update_profile_phone",          Backing::Mtproto },
	{"update_profile_photo_privacy",  Backing::Mtproto },
	{"update_profile_username",       Backing::Mtproto },
	{"update_quick_reply",            Backing::LocalOnly },
	{"update_scheduled",              Backing::LocalOnly },
	{"update_task",                   Backing::LocalOnly },
	{"upload_avatar_source",          Backing::LocalOnly },
	{"use_quick_reply",               Backing::Mtproto },
	{"withdraw_earnings",             Backing::Mtproto },
});

// Backing recorded for `name`, or Unimplemented when the name is unknown --
// an unknown tool is by definition backed by nothing, so the safe answer and
// the truthful one coincide.
[[nodiscard]] Backing ToolBackingFor(std::string_view name);

// Whether `name` appears in the table at all. Distinguishes "recorded as
// unbacked" from "never recorded", which ToolBackingFor() deliberately
// collapses.
[[nodiscard]] bool ToolBackingKnown(std::string_view name);

// Human-readable label used in tool descriptions and error messages.
[[nodiscard]] std::string_view BackingName(Backing backing);

// Verifies the table is sorted, free of duplicates, and in sync with the
// registered handlers. Called once at startup; asserts in debug builds and
// logs in release so a drifted table is visible either way.
void VerifyToolBackings(const QStringList &registeredToolNames);

} // namespace MCP
